version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://catapi@postgres/catapi
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: catapi
      POSTGRES_DB: catapi